# 服务端口
server:
  port: 8003
  # 服务名
spring:
  application:
    name: service-vod
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB  # 最大值总上传的数据大小 ：默认10M
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI5tJ938eEwf9BkvjzSTcp
      keysecret: K7DDAxQamNLtUImDGoklXpkdU5wnJh
