# 服务端口
server:
  port: 8004
  # 服务名
spring:
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli01?serverTimezone=GMT%2B8
    username: root
    password: root
    #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis配置
  redis:
    host: 192.168.207.131
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/atguigu/educms/mapper/xml/*.xml
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl